/********************************************************************
* /home/roel/alice/ali-master/conversionMacro/classes/dictionaries/ConversionAnalysis_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/roel/alice/ali-master/conversionMacro/classes/dictionaries/ConversionAnalysis_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableConversionAnalysis_dict();
extern void G__cpp_setup_inheritanceConversionAnalysis_dict();
extern void G__cpp_setup_typetableConversionAnalysis_dict();
extern void G__cpp_setup_memvarConversionAnalysis_dict();
extern void G__cpp_setup_globalConversionAnalysis_dict();
extern void G__cpp_setup_memfuncConversionAnalysis_dict();
extern void G__cpp_setup_funcConversionAnalysis_dict();
extern void G__set_cpp_environmentConversionAnalysis_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/roel/alice/ali-master/conversionMacro/classes/ConversionAnalysis.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ConversionAnalysis_dictLN_TClass;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TBuffer;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMemberInspector;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TObject;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TNamed;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TTask;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_AliAnalysisTask;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_AliAnalysisTaskSE;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_TRandom2;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_AliO2Timeframe;
extern G__linked_taginfo G__ConversionAnalysis_dictLN_ConversionAnalysis;

/* STUB derived class for protected member access */
